### ISSUE TITLE
Support documents in strict format

### ISSUE THREAD

**Issue by teajaysee** [mwilliamson/mammoth.js#146]
I get the following error on windows using Node 8.9.4 .. wonder if anyone has any ideas?
thanks

Fatal TypeError: Cannot read property 'children' of undefined
    at Object.convertXmlToDocument (C:\Users\Tom\mammmoth2\node_modules\mammoth\lib\docx\document-xml-reader.js:13:54)
    at C:\Users\Tom\mammmoth2\node_modules\mammoth\lib\docx\docx-reader.js:71:39
    at Result.flatMap (C:\Users\Tom\mammmoth2\node_modules\mammoth\lib\results.js:20:22)
    at C:\Users\Tom\mammmoth2\node_modules\mammoth\lib\docx\docx-reader.js:65:44
    at Result.flatMap (C:\Users\Tom\mammmoth2\node_modules\mammoth\lib\results.js:20:22)
    at C:\Users\Tom\mammmoth2\node_modules\mammoth\lib\docx\docx-reader.js:64:37
    at C:\Users\Tom\mammmoth2\node_modules\mammoth\lib\docx\docx-reader.js:108:24
    at tryCatcher (C:\Users\Tom\mammmoth2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Tom\mammmoth2\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Tom\mammmoth2\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Tom\mammmoth2\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Tom\mammmoth2\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Tom\mammmoth2\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Tom\mammmoth2\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Tom\mammmoth2\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)

**Comment by jedidiah81** [comment]
No, basically I think i've tracked it down that it happens when a document is saved as .doc first then saved as .docx in Word. If i copy the contents of the one it happened for into a new document and save it first time as docx then it works. Using Word 16.

**Comment by mwilliamson** [comment]
Thanks for the further details. Could you provide an example document? Otherwise it's rather hard for me to track down the issue.

**Comment by jedidiah81** [comment]
yep, here you go
[testdoc.docx](https://github.com/mwilliamson/mammoth.js/files/1652413/testdoc.docx)

**Comment by mwilliamson** [comment]
Looks like the XML namespace is different i.e. `xmlns:w="http://purl.oclc.org/ooxml/wordprocessingml/main"`. A bit of searching suggests that this is due to the document being in strict mode, which implies that some of the other namespaces will be different as well.

**Comment by jedidiah81** [comment]
Thanks - yes sorry I didn't realise there was a difference and saved as non-strict-mode it works fine.

**Comment by mwilliamson** [comment]
No worries, the UI doesn't really make the mode particularly prominent,
so it's easily missed. Mammoth should handle both modes in any case.

**Comment by Philrobots** [comment]
Has there been any progress on this issue?

I've just encountered the same error

@mwilliamson 

File : 
[CorrumptFile.docx](https://github.com/mwilliamson/mammoth.js/files/13756714/CorrumptFile.docx)

**Comment by Philrobots** [comment]
Has there been any progress on this?

I made the same mistake

**Comment by mwilliamson** [comment]
> Has there been any progress on this?

Nope!

**Comment by mwilliamson** [comment]
Support for the strict format has been added in the latest commit. It's possible that are relevant discrepancies between the strict and transitional formats beyond just the namespaces used: if that turns out to the case, feel free to open specific issues.
