### ISSUE TITLE
Attempting to convert docx file from S3

### ISSUE THREAD

**Issue by campgurus** [mwilliamson/mammoth.js#235]
The package works great for internal files with local/relative urls like: 

/Users/dariusgoore/Downloads/1585930968750.docx

However, the files I need to convert are in an S3 bucket with urls like this one:

https://writerboard-production.s3.amazonaws.com/1585935462485.docx 

In these cases I get the following error:

```
Fatal Error: ENOENT: no such file or directory, open 'https://writerboard-production.s3.amazonaws.com/1585935462485.docx '
    at Object.openZip (/Users/dariusgoore/development/writerboard/writerboard-express-api/node_modules/mammoth/lib/unzip.js:14:16)
    at convert (/Users/dariusgoore/development/writerboard/writerboard-express-api/node_modules/mammoth/lib/index.js:34:18)
    at Object.convertToHtml (/Users/dariusgoore/development/writerboard/writerboard-express-api/node_modules/mammoth/lib/index.js:22:12)
    at router.put (/Users/dariusgoore/development/writerboard/writerboard-express-api/src/routes/uploads.js:33:11)
```

**Comment by mwilliamson** [comment]
if you're using node.js, only paths or buffers are supported, so you'll have to download your document either to a local file or to an in-memory buffer.

**Comment by campgurus** [comment]
Ok thanks for that clarification. Hosted on Heroku, so I'll have to find an in-memory solution.  Thanks.
