### ISSUE TITLE
I'm being dumb..  Can't get "center" to fire

### ISSUE THREAD

**Issue by JohnMcLear** [mwilliamson/mammoth.js#24]
docx looks good, I see `w:val=center`

But this config doesn't seem to be work

```
    styleMap: [
      "p[style-name='center'] => p:fresh > p:center",
...
```

Any idea what I'm doing wrong?

**Comment by JohnMcLear** [comment]
Ugh the docx-reader no longer woks

```
[root@etherpad ep_mammoth]# node test.js
Testing /tmp/testDoc.docx
/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/lib/docx/office-xml-reader.js:32
    if (docxFile.exists(path)) {
                 ^
TypeError: undefined is not a function
    at readXmlFromZipFile (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/lib/docx/office-xml-reader.js:32:18)
    at /home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/lib/docx/docx-reader.js:83:16
    at Object.read (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/lib/docx/docx-reader.js:24:23)
    at Object.<anonymous> (/home/etherpad-lite/node_modules/ep_mammoth/test.js:8:41)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

It looks lik the function ``require("mammoth/lib/docx/docx-reader").read({path: docxPath})`` has changed
