### ISSUE TITLE
Fatal TypeError: Cannot read property 'numStyleLink' of undefined

### ISSUE THREAD

**Issue by justwink** [mwilliamson/mammoth.js#247]
The following error occurs when I parse my DOCx
```
Fatal TypeError: Cannot read property 'numStyleLink' of undefined
    at Object.findLevel (C:\Users\15820\Desktop\test\node_modules\_mammoth@1.4.9@mammoth\lib\docx\numbering-xml.js:10:29)
    at readNumberingProperties (C:\Users\15820\Desktop\test\node_modules\_mammoth@1.4.9@mammoth\lib\docx\body-reader.js:489:26)
    at C:\Users\15820\Desktop\test\node_modules\_mammoth@1.4.9@mammoth\lib\docx\body-reader.js:194:32
    at C:\Users\15820\Desktop\test\node_modules\_mammoth@1.4.9@mammoth\lib\docx\body-reader.js:577:16
    at Result.map (C:\Users\15820\Desktop\test\node_modules\_mammoth@1.4.9@mammoth\lib\results.js:16:23)
    at ReadResult.map (C:\Users\15820\Desktop\test\node_modules\_mammoth@1.4.9@mammoth\lib\docx\body-reader.js:576:31)
    at w:pPr (C:\Users\15820\Desktop\test\node_modules\_mammoth@1.4.9@mammoth\lib\docx\body-reader.js:188:48)
    at readXmlElement (C:\Users\15820\Desktop\test\node_modules\_mammoth@1.4.9@mammoth\lib\docx\body-reader.js:41:24)
    at Array.map (<anonymous>)
    at readXmlElements (C:\Users\15820\Desktop\test\node_modules\_mammoth@1.4.9@mammoth\lib\docx\body-reader.js:33:32)
    at w:p (C:\Users\15820\Desktop\test\node_modules\_mammoth@1.4.9@mammoth\lib\docx\body-reader.js:177:20)
    at readXmlElement (C:\Users\15820\Desktop\test\node_modules\_mammoth@1.4.9@mammoth\lib\docx\body-reader.js:41:24)
    at Array.map (<anonymous>)
    at Object.readXmlElements (C:\Users\15820\Desktop\test\node_modules\_mammoth@1.4.9@mammoth\lib\docx\body-reader.js:33:32)
    at Object.readXmlElements (C:\Users\15820\Desktop\test\node_modules\_mammoth@1.4.9@mammoth\lib\docx\body-reader.js:17:44)
    at Object.convertXmlToDocument (C:\Users\15820\Desktop\test\node_modules\_mammoth@1.4.9@mammoth\lib\docx\document-xml-reader.js:13:33)
```

### Mammoth version
@1.4.9

### File position
node_modules\_mammoth@1.4.9@mammoth\lib\docx\numbering-xml.js 

### Case
```
const mammoth = require('mammoth')
const fs = require('fs')

const buffer = fs.readFileSync('./mammoth.docx')

mammoth
  .convertToMarkdown({ buffer })
  .then(function (result) {
    console.log(result.value)
  })
  .done()

```

And the source code of the error is：
```
function Numbering(nums, abstractNums, styles) {
    function findLevel(numId, level) {
        var num = nums[numId];
        if (num) {
            var abstractNum = abstractNums[num.abstractNumId];
            if (abstractNum.numStyleLink == null) {
                return abstractNums[num.abstractNumId].levels[level];
            } else {
                var style = styles.findNumberingStyleById(abstractNum.numStyleLink);
                return findLevel(style.numId, level);
            }
        } else {
            return null;
        }
    }

    return {
        findLevel: findLevel
    };
}
```

### When I simply enhanced the robustness of the code, it seemed to work:
```
var num = nums[numId];
var abstractNum = abstractNums[num.abstractNumId];

if (num && abstractNum ) {
        if (abstractNum.numStyleLink == null) {
     ...
     ...
```

So... where might things go wrong?

Thx!

**Comment by justwink** [comment]
mammoth@1.4.7 works！

**Comment by justwink** [comment]
mammoth@1.4.8 has the same issue！

**Comment by justwink** [comment]
> mammoth@1.4.7 works！

![image](https://user-images.githubusercontent.com/24563265/87752486-120dc100-c833-11ea-8338-4887e30155a9.png)
However, some empty tags or escaped symbols are maintained...
Sad story...

**Comment by mwilliamson** [comment]
Could you provide a minimal example file?
