### ISSUE TITLE
Can't find end of central directory

### ISSUE THREAD

**Issue by eclecsis** [mwilliamson/mammoth.js#248]
Using extractRawText on docx files has always worked as expected in my project, but for one especially long file it is throwing this error in the browser: `Unhandled Rejection (Error): Can't find end of central directory : is this a zip file ? If it is, see http://stuk.github.io/jszip/documentation/howto/read_zip.html`

The code I'm using is just:

```
const arrayBuffer = await document.arrayBuffer()
const result = await mammoth.extractRawText({ arrayBuffer })
```

and that is where it errors out. This is in Chrome.

The document is not a zip file and is not corrupted; I can open it in Microsoft Word as expected. Since jszip is a mammoth dependency instead of a dependency of my project I'm not sure how to handle. Is this a known issue?

**Comment by mwilliamson** [comment]
Could you post the full code that you're using, and provide an example document? docx files are normally zip files: if your particular docx file isn't a zip file, then Mammoth doesn't currently support it.

**Comment by eclecsis** [comment]
Interesting, was not aware that .docx were zip files.

It's this document: 
[Hopkins_Vorlage Steuerrecht Daten.docx](https://github.com/mwilliamson/mammoth.js/files/5095787/Hopkins_Vorlage.Steuerrecht.Daten.docx)

Not sure what more code you want as the above is where it breaks ...

```
import mammoth from 'mammoth'

const extractVariables = async (templateUrl) => {
  const document = await fetch(templateUrl)
  const arrayBuffer = await document.arrayBuffer()
  const result = await mammoth.extraRawText({ arrayBuffer })
  const documentContent = result.value
 // a bunch of regex operations dependent on documentContent
}
```

**Comment by mwilliamson** [comment]
I've just tried using Mammoth on node to read that file, and it seems to work just fine. Are you sure that the array buffer contains the entire file? Could you check the byte length is correct?

**Comment by mwilliamson** [comment]
I'm closing since I don't think there's anything else I can do at the moment, but feel free to reopen with more information.

**Comment by joshxyzhimself** [comment]
This is a weird one, sometimes it works, sometimes it doesn't.

Node.js: 12.14.1
OS: Linux x64 5.4.0-37-generic snap

```
const file_buffer = await fs.promises.readFile(path.join(file.dirname, file.filename));
const file_hash = crypto.createHash('sha256').update(file_buffer).digest('hex');
const file_html = await mammoth.convertToHtml({ buffer: file_buffer });
```

```
(node:765642) UnhandledPromiseRejectionWarning: Error: Can't find end of central directory : is this a zip file ? If it is, see http://stuk.github.io/jszip/documentation/howto/read_zip.html
    at ZipEntries.readEndOfCentral (/node_modules/jszip/lib/zipEntries.js:149:23)
    at ZipEntries.load (/node_modules/jszip/lib/zipEntries.js:215:14)
    at new ZipEntries (/node_modules/jszip/lib/zipEntries.js:21:14)
    at JSZip.module.exports [as load] (/node_modules/jszip/lib/load.js:11:18)
    at new JSZip (/node_modules/jszip/lib/index.js:39:14)
    at Object.openArrayBuffer (/node_modules/mammoth/lib/zipfile.js:10:19)
    at Object.openZip (/node_modules/mammoth/lib/unzip.js:16:41)
    at convert (/node_modules/mammoth/lib/index.js:34:18)
    at Object.convertToHtml (/node_modules/mammoth/lib/index.js:22:12)
    at /scripts/parsers/file.js:61:39
    at async Promise.all (index 5)
    at async recurse_files (/scripts/parsers/file.js:58:5)
```

**Comment by joshxyzhimself** [comment]
Lol got it, it happens when one of the files is open (which creates a lock file in the directory)

Something like this:

```
.~lock.FILENAME.docx#
```

**Comment by shaozhitao** [comment]
Only support .docx, use .doc will report this error.
只支持docx ,不支持doc

**Comment by NoelAbrahams** [comment]
I still think that this is some sort of bug induced by a race condition somewhere. We are getting this error intermittently, without our doing anything different between calls. Here's the stack from the error:

```
Error: Corrupted zip : can't find end of central directory
    at new ZipEntries (c:\foo\node_modules\jszip\lib\zipEntries.js:21:14)
    at JSZip.module.exports [as load] (c:\foo\node_modules\jszip\lib\load.js:11:18)
    at new JSZip (c:\foo\node_modules\jszip\lib\index.js:39:14)
    at openArrayBuffer (c:\foo\node_modules\mammoth\lib\zipfile.js:10:19)
    at bound (node:domain:413:15)
    at runBound (node:domain:424:12)
    at tryCatcher (c:\foo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\foo\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (c:\foo\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (c:\foo\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (c:\foo\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (c:\foo\node_modules\bluebird\js\release\promise.js:636:18)
    at c:\foo\node_modules\bluebird\js\release\nodeback.js:42:21
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:73:3)
```
