### ISSUE TITLE
Buffer in not defined

### ISSUE THREAD

**Issue by lattemisa** [mwilliamson/mammoth.js#313]
Hello, I am having issues getting `.convertToMarkdown` working in the browser.
I am having a listener `onChange` with function handling parsing as follow:
```
const handleParse = (event) => {
    const reader = new FileReader();
    reader.readAsArrayBuffer(event.target.files[0]);
    reader.onloadend = (evt) => {
      if (evt.target.readyState === FileReader.DONE) {
        const arrayBuffer = evt.target.result;
        const array = new Uint8Array(arrayBuffer);
        mammoth
          .convertToHtml({ arrayBuffer: array })
          .then((res) => {
            console.log(res, "<<<here2");
          })
          .catch((err) => {
            console.log(err);
          });
      }
    };
  };
```

But i am still getting ReferenceError : 
```
ReferenceError: Buffer is not defined
    at uint8ArrayToBuffer (zipfile.js:42:1)
    at zipfile.js:15:1
```

Any help would be appreciated.

**Comment by mwilliamson** [comment]
How are you using Mammoth? If it's in the browser, you'll probably want to use the browser build i.e. `mammoth.browser.js` or `mammoth.browser.min.js`.

**Comment by mwilliamson** [comment]
Closing since I don't think this can be debugged without more information.
