### ISSUE TITLE
vite and vue3 项目引入报错

### ISSUE THREAD

**Issue by dazuo-art** [mwilliamson/mammoth.js#327]
import  mammoth from "mammoth";

vue-router.esm-bundler.js:3302 TypeError: Cannot read properties of undefined (reading 'prototype')
    at sax.js:221:46
    at node_modules/sax/lib/sax.js (sax.js:1570:32)
    at __require2 (chunk-UC7LELEO.js?v=c9120286:48:44)
    at node_modules/mammoth/lib/xml/reader.js (reader.js:2:11)
    at __require2 (chunk-UC7LELEO.js?v=c9120286:48:44)
    at node_modules/mammoth/lib/xml/index.js (index.js:6:22)
    at __require2 (chunk-UC7LELEO.js?v=c9120286:48:44)
    at node_modules/mammoth/lib/docx/office-xml-reader.js (office-xml-reader.js:4:11)
    at __require2 (chunk-UC7LELEO.js?v=c9120286:48:44)
    at node_modules/mammoth/lib/docx/docx-reader.js (docx-reader.js:11:26)
    at __require2 (chunk-UC7LELEO.js?v=c9120286:48:44)
    at node_modules/mammoth/lib/index.js (index.js:3:18)
    at __require2 (chunk-UC7LELEO.js?v=c9120286:48:44)
    at dep:mammoth:1:16

**Comment by mwilliamson** [comment]
Could you provide minimal reproduction steps, including a minimal example document?

**Comment by dazuo-art** [comment]
https://github.com/dazuo-art/viteAndMammoth.git
&nbsp;


布朗狗熊。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Michael ***@***.***&gt;; 
发送时间: 2022年6月18日(星期六) 上午6:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mwilliamson/mammoth.js] vite and vue3 项目引入报错 (Issue #327)





 
Could you provide minimal reproduction steps, including a minimal example document?

**Comment by dazuo-art** [comment]
Vite to 3.0.0-alpha.10

**Comment by agreenbird1** [comment]
大佬咋解决的呢

**Comment by dazuo-art** [comment]
升级vite版本，至少Vite3.0.0-alpha.10


布朗狗熊。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mwilliamson/mammoth.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月29日(星期四) 上午10:01
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [mwilliamson/mammoth.js] vite and vue3 项目引入报错 (Issue #327)





 
大佬咋解决的呢
