### ISSUE TITLE
Could not find file in options

### ISSUE THREAD

**Issue by happymalyo** [mwilliamson/mammoth.js#334]
## Issue description
I get an error when using mammoth.convertToHtml(...) in a native javascript app with an existing .docx file.

## Steps to reproduce the issue
1. Get mammoth using cdn link: https://cdnjs.cloudflare.com/ajax/libs/mammoth/1.4.9/mammoth.browser.js
2. Add a .docx file in a specific folder (make sure you can access it)
3. Load the .docx file, convert it into  html then use mammoth.convertToHtml({path: "/path/to/myDoc.docx"});
## What's the expected result?
- The .docx file is converted to HTML
## What's the actual result?
Uncaught Error: Could not find file in options
    at Object.openZip (mammoth.browser.js:108:32)
    at convert (mammoth.browser.js:2369:18)
    at Object.convertToHtml (mammoth.browser.js:2357:12)
## Additional details / screenshot
Here is my code

 `
  mammoth.convertToHtml ({path: "/path/to/myDoc.docx"}) 
          .then(function(result){
              var html = result.value; 
              result1.innerHTML = html
              var messages = result.messages; 
      })
      .done();
`

OS and version : Linux Mint 19.2 Tina
Browser : Chrome Version 103.0.5060.134 
Stack : Javascript

**Comment by mwilliamson** [comment]
If you're using mammoth in a browser rather than node.js, you'll need to pass an array buffer rather than a path.

**Comment by happymalyo** [comment]
> If you're using mammoth in a browser rather than node.js, you'll need to pass an array buffer rather than a path.

Thaks for replying me. I need to use an existing file. Could you tell how to convert the file to a buffer without uploading

**Comment by mwilliamson** [comment]
That'll depend on your own system and how files are stored, which isn't something I can help with I'm afraid.

**Comment by happymalyo** [comment]
> That'll depend on your own system and how files are stored, which isn't something I can help with I'm afraid.

That's right! I will try my best then. Thank you
