### ISSUE TITLE
Error when upgrading Node and Webpack

### ISSUE THREAD

**Issue by jeffreytli** [mwilliamson/mammoth.js#352]
Hello there! I'm currently running into an issue with mammoth after having upgraded to Webpack 5 and  Node 18. This is what our code currently looks like:
```
import mammoth from 'mammoth';

mammoth.convertToHtml(this.state.arrayBuffer, options)
      .then(result => this.props.notifyOnImportUpdate(result.value, true))
      .done(); 
````

However, this is the error that we're currently getting:
```
app.bundle.js:22299 Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at eval (sax.js:221:46)
    at eval (sax.js:1574:3)
    at ../../node_modules/sax/lib/sax.js (app.bundle.js:19206:1)
    at __webpack_require__ (app.bundle.js:22296:33)
    at fn (app.bundle.js:22534:21)
    at eval (reader.js:2:11)
    at ../../node_modules/mammoth/lib/xml/reader.js (app.bundle.js:16408:1)
    at __webpack_require__ (app.bundle.js:22296:33)
    at fn (app.bundle.js:22534:21)
    at eval (index.js:6:22)
    at ../../node_modules/mammoth/lib/xml/index.js (app.bundle.js:16388:1)
    at __webpack_require__ (app.bundle.js:22296:33)
    at fn (app.bundle.js:22534:21)
    at eval (office-xml-reader.js:4:11)
    at ../../node_modules/mammoth/lib/docx/office-xml-reader.js (app.bundle.js:16158:1)
    at __webpack_require__ (app.bundle.js:22296:33)
```

Do you have any ideas around how to resolve this issue? Thank you very much!

**Comment by mp5healer** [comment]
> import mammoth from 'mammoth';

Doest this `import * as mammoth from "mammoth/mammoth.browser.js"`;
or this `import * as mammoth from "mammoth/mammoth.browser"`;
resolves the issue ?

**Comment by mwilliamson** [comment]
It depends on exactly what's undefined, but if I had to guess, you're missing a polyfill for one of the modules in the node standard library that Mammoth (transitively) depends on. As described above, on option is to use a bundled build of Mammoth. The other is to provide polyfills for the missing modules.

**Comment by mwilliamson** [comment]
Closing since I don't think there's anything else to in the absence of more information.
