### ISSUE TITLE
Getting "Cannot read properties of undefined (reading 'attributes')" when parsing a numbered list

### ISSUE THREAD

**Issue by jhpbipsync** [mwilliamson/mammoth.js#393]
I'm getting the following error when parsing some docx files. I've fixed it on a fork, the issue appears to be that within a `w:ilvl` there is no `w:numFmt` element and therefore we cant check the attributes to set the `numFmt` variable.
```
 Cannot read properties of undefined (reading 'attributes')
    at ..../node_modules/mammoth/lib/docx/numbering-xml.js:70:52
    at Array.forEach (<anonymous>)
    at ..../node_modules/mammoth/lib/docx/numbering-xml.js:67:43)
    at ..../node_modules/mammoth/lib/docx/numbering-xml.js:60:28
    at Array.forEach (<anonymous>)
    at readAbstractNums (..../node_modules/mammoth/lib/docx/numbering-xml.js:58:48)
    at Object.readNumberingXml (..../node_modules/mammoth/lib/docx/numbering-xml.js:51:24)
    at Object.readElement (..../node_modules/mammoth/lib/docx/docx-reader.js:204:33)
    at ..../node_modules/mammoth/lib/docx/docx-reader.js:161:42
```

I cant provide the original document but here's is a snippet of the screenshot of the document, as you can see the number format for the list is a little off and its just repeating a 1. 

**Screenshot**
<img width="58" alt="Screenshot 2024-03-20 at 15 23 04" src="https://github.com/mwilliamson/mammoth.js/assets/106114851/29522de7-a757-4257-bd66-4e825f055761">

I have fixed this on a fork by checking for that attribute and falling back to a default of `numFmt = 'number'`

**Comment by jhpbipsync** [comment]
Thank you @mwilliamson, working perfectly now.
