### ISSUE TITLE
Error: Non-whitespace before first tag.

### ISSUE THREAD

**Issue by JohnMcLear** [mwilliamson/mammoth.js#44]
```
[2015-04-20 15:03:06.562] [ERROR] console - Error: Non-whitespace before first tag.
    at error (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/node_modules/sax/lib/sax.js:642:8)
    at strictFail (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/node_modules/sax/lib/sax.js:662:22)
    at Object.write (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/node_modules/sax/lib/sax.js:934:11)
    at Object.read (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/lib/xmlreader.js:75:12)
    at read (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/lib/office-xml-reader.js:19:22)
    at _fulfilled (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/node_modules/q/q.js:760:13)
    at /home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/node_modules/q/q.js:574:44
    at flush (/home/etherpad-lite/node_modules/ep_mammoth/node_modules/mammoth/node_modules/q/q.js:108:17)
```
https://github.com/JohnMcLear/ep_mammoth/issues/4

Not sure on STR, just spotted this issue and thought right place to report is here.

**Comment by mwilliamson** [comment]
What version of Mammoth are you using? This can happen if the XML has a BOM at the start, but Mammoth strips those out since 0.3.10 (and to the best of my recollection, Mammoth hasn't used q for promises for quite some time).

**Comment by JohnMcLear** [comment]
0.3.0 -- https://github.com/JohnMcLear/ep_mammoth/blob/master/package.json#L12

I will update and see if it fixes it.  Should there be any breaking changes?

**Comment by mwilliamson** [comment]
Not that I can think of. Full change notes in `NEWS` if you want to peruse them though.

**Comment by JohnMcLear** [comment]
Took a read through, don't see anything crippling, thanks for the new element support too!  +1 :)
