### ISSUE TITLE
when i use in Nodejs,i got an error

### ISSUE THREAD

**Issue by licongmu** [mwilliamson/mammoth.js#65]
Hi Michael,i use the mammoth like that:

var mammoth = require("mammoth");
 mammoth.convertToHtml({path: "./test.docx"})
    .then(function(result){
        var html = result.value; // The generated HTML
        var messages = result.messages; // Any messages, such as warnings during conversion
    })
    .done();

but i got so many errors,it told that: can't find end of central directory:is this a zip file?if it is,see XXXX.

what's wrong with me?please give me some help,tks

**Comment by mwilliamson** [comment]
Could you copy and paste the actual error you get?

Can you open the document as a ZIP file using an archive extractor? It sounds to me as though it's not actually a ZIP file (.docx files are ZIP files).

**Comment by licongmu** [comment]
E:\yanneng\yanneng\node_modules\mammoth\node_modules\bluebird\js\main\async.js:95
                throw res.e;
                ^

Error: Can't find end of central directory : is this a zip file ? If it is, see http://stuk.github.io/jszip/documentation/howto/read_zip.html
    at Object.ZipEntries.readEndOfCentral (E:\yanneng\yanneng\node_modules\mammoth\node_modules\jszip\lib\zipEntries.js:149:23)
    at Object.ZipEntries.load (E:\yanneng\yanneng\node_modules\mammoth\node_modules\jszip\lib\zipEntries.js:215:14)
    at Object.ZipEntries (E:\yanneng\yanneng\node_modules\mammoth\node_modules\jszip\lib\zipEntries.js:21:14)
    at Object.module.exports [as load] (E:\yanneng\yanneng\node_modules\mammoth\node_modules\jszip\lib\load.js:11:18)
    at Object.JSZip (E:\yanneng\yanneng\node_modules\mammoth\node_modules\jszip\lib\index.js:39:14)
    at openArrayBuffer (E:\yanneng\yanneng\node_modules\mammoth\lib\zipfile.js:8:19)
    at tryCatch1 (E:\yanneng\yanneng\node_modules\mammoth\node_modules\bluebird\js\main\util.js:45:21)
    at Promise$_callHandler [as _callHandler] (E:\yanneng\yanneng\node_modules\mammoth\node_modules\bluebird\js\main\promise.js:660:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (E:\yanneng\yanneng\node_modules\mammoth\node_modules\bluebird\js\main\promise.js:675:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (E:\yanneng\yanneng\node_modules\mammoth\node_modules\bluebird\js\main\promise.js:845:14)


E:\yannneg\yanneng is my project's root.

**Comment by mwilliamson** [comment]
And you're sure that the path is correct, and that the file is indeed a zip file?

**Comment by licongmu** [comment]
i get it ! it's due to the docx is empty,i add something to it then become normal ! thk!

**Comment by mwilliamson** [comment]
Glad you got it working.
