### ISSUE TITLE
Inconsistent ability to work on docx files that are currently open

### ISSUE THREAD

**Issue by MCTaylor17** [mwilliamson/mammoth.js#72]
I'm getting an error converting a file.  It goes away after the file is closed.  I think it may have to do with the fact that the docx in question had been saved on a Mac.

Here is the stack trace:

```
Possibly unhandled Error: Can't find end of central directory : is this a zip file ? If it is, see http://stuk.github.io/jszip/documentation/howto/read_zip.html

    at Object.ZipEntries.readEndOfCentral (X:\{path}\node_modules\mammoth\node_modules\jszip\lib\zipEntries.js:149:23)
    at Object.ZipEntries.load (X:\{path}\node_modules\mammoth\node_modules\jszip\lib\zipEntries.js:215:14)
    at Object.ZipEntries (X:\{path}\node_modules\mammoth\node_modules\jszip\lib\zipEntries.js:21:14)
    at Object.module.exports [as load] (X:\{path}\node_modules\mammoth\node_modules\jszip\lib\load.js:11:18)
    at Object.JSZip (X:\{path}\node_modules\mammoth\node_modules\jszip\lib\index.js:39:14)
    at openArrayBuffer (X:\{path}\node_modules\mammoth\lib\zipfile.js:8:19)
    at tryCatch1 (X:\{path}\node_modules\mammoth\node_modules\bluebird\js\main\util.js:45:21)
    at Promise$_callHandler [as _callHandler] (X:\{path}\node_modules\mammoth\node_modules\bluebird\js\main\promise.js:660:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (X:\{path}\node_modules\mammoth\node_modules\bluebird\js\main\promise.js:675:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (X:\{path}\node_modules\mammoth\node_modules\bluebird\js\main\promise.js:845:14)
```

**Comment by mwilliamson** [comment]
Can you successfully read it using other applications, such as an archive manager?

I don't think Mammoth is doing anything particularly esoteric, so this might be an issue with JSZip.

**Comment by mwilliamson** [comment]
In fact, Mammoth either just uses `readFile` and passes an array buffer to JSZip, so I'm not sure there's anything that Mammoth can do to handle this any better. Certainly open to suggestions, but closing this in the meantime.
