### ISSUE TITLE
Cannot read property root of null

### ISSUE THREAD

**Issue by smith-kyle** [mwilliamson/mammoth.js#73]
```javascript
const filePath = '/path/to/docx/file/1.0.0.docx';
return mammoth.convertToHtml({path: filePath})
  .catch(e => console.error(e.stack);
```

```

TypeError: Cannot read property 'root' of null
    at Object.convertXmlToDocument (/Users/kyles/dev/git-projects/git-kraken/build/node_modules/mammoth/lib/docx/document-xml-reader.js:11:31)
    at /Users/kyles/dev/git-projects/git-kraken/build/node_modules/mammoth/lib/docx/docx-reader.js:60:31
    at Result.flatMap (/Users/kyles/dev/git-projects/git-kraken/build/node_modules/mammoth/lib/results.js:19:22)
    at /Users/kyles/dev/git-projects/git-kraken/build/node_modules/mammoth/lib/docx/docx-reader.js:55:33
    at /Users/kyles/dev/git-projects/git-kraken/build/node_modules/mammoth/lib/docx/docx-reader.js:93:24
    at tryCatch1 (/Users/kyles/dev/git-projects/git-kraken/build/node_modules/mammoth/node_modules/bluebird/js/main/util.js:45:21)
    at Promise$_callHandler [as _callHandler] (/Users/kyles/dev/git-projects/git-kraken/build/node_modules/mammoth/node_modules/bluebird/js/main/promise.js:660:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/kyles/dev/git-projects/git-kraken/build/node_modules/mammoth/node_modules/bluebird/js/main/promise.js:675:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/Users/kyles/dev/git-projects/git-kraken/build/node_modules/mammoth/node_modules/bluebird/js/main/promise.js:845:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/Users/kyles/dev/git-projects/git-kraken/build/node_modules/mammoth/node_modules/bluebird/js/main/async.js:77:12
```

Not sure what's going on here. Let me know if you want me to provide any more information.

**Comment by mwilliamson** [comment]
An example file would be helpful if possible.

**Comment by smith-kyle** [comment]
I'm sorry the file was corrupted somehow so it's not on mammoth's end. Thanks for the quick response!

**Comment by mwilliamson** [comment]
No problem, glad you got it sorted.
